### ISSUE TITLE
take5 missing configs

### ISSUE THREAD

**Issue by migeed-z** [migeed-z/retic_performance#13]
Take5 is missing 5k configurations. Current number we have is  60132 and we expect 65536 configurations.

**Comment by bennn** [comment]
Nodes were working on most of those missing configs. If there are nodes running & you want to count configurations:
- to count outputs, use `wc -l karst_output.txt Test/*/node_output.txt`
- to count inputs, use `wc -l karst_input.txt Test/*/node_input.txt`

But problem! Somehow `take5` has some bad configurations as input --- configurations for more than 3 files, like `0-11-7-1`

Here they all are:
[take5_bad_input.txt](https://github.com/migeed-z/retic_performance/files/531245/take5_bad_input.txt)

**Comment by bennn** [comment]
Okay, updated take5's configs on the cluster with these outputs:
[take5_checkpoint.txt.tar.gz](https://github.com/migeed-z/retic_performance/files/531274/take5_checkpoint.txt.tar.gz)

and these inputs:
[take5_input.tar.gz](https://github.com/migeed-z/retic_performance/files/531275/take5_input.tar.gz)

**Comment by migeed-z** [comment]
I am still observing the bad configs in the output file. Is that expected? or are they removed after all configs run?

**Comment by bennn** [comment]
No that is not expected.
- the last output file I posted should have only good configs

Do you have time to figure out which configs from the last input file are going wrong?

**Comment by bennn** [comment]
updated again
- 59762 finished 
  [take5_output.txt.tar.gz](https://github.com/migeed-z/retic_performance/files/562495/take5_output.txt.tar.gz)
- 5774 missing 
  [take5_input.txt](https://github.com/migeed-z/retic_performance/files/562494/take5_input.txt)

**Comment by bennn** [comment]
Also updated Evolution:
- 5812 done
- 518476 missing

[Evolution.tar.gz](https://github.com/migeed-z/retic_performance/files/562508/Evolution.tar.gz)
