### ISSUE TITLE
No module named `futen`

### ISSUE THREAD

**Issue by bennn** [migeed-z/retic_performance#15]
An error from the logs:

```
Traceback (most recent call last):
  File "/tmp/1788679.m2/reticulated/retic.py", line 5, in <module>
    retic.main()
  File "/tmp/1788679.m2/reticulated/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/tmp/1788679.m2/reticulated/retic/retic.py", line 104, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/tmp/1788679.m2/reticulated/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/tmp/1788679.m2/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "/N/u/zmahmoud/Karst/retic_performance/futen//Test/1788679.m2/main.py", line 259, in <module>
ImportError: No module named 'futen'
```

Guess: the node is running a bad `futen` config, and tried to copy in a version of `futen.py` that doesn't exist

**Comment by bennn** [comment]
Well, updated `futen`'s inputs and outputs. There's only a few hundred missing.

Here's both in 1 folder:
[futen.tar.gz](https://github.com/migeed-z/retic_performance/files/531290/futen.tar.gz)

**Comment by migeed-z** [comment]
We have 32517 out of 32768 configurations finished. But there is no input file.

**Comment by bennn** [comment]
Did you check whether nodes running `futen` (in the `futen/Test/` folder) have the missing inputs?

When a node runs `bnode.sh` it:
- Locks a benchmark's input file
- Reads [`CHUNK`](https://github.com/migeed-z/retic_performance/blob/master/karst/bnode.sh#L122) configurations from the main input file to a private file
- Releases the lock, runs those `CHUNK` configurations privately

When the node dies, `brun.py` is responsible for putting the results on the main output file & putting unfinished inputs back on the benchmark's input file.

**Comment by bennn** [comment]
These are the missing futen configs. They're on the cluster as `karst_input.txt2` for next time.
[futen-missing.txt](https://github.com/migeed-z/retic_performance/files/562308/futen-missing.txt)
