### ISSUE TITLE
No data for http

### ISSUE THREAD

**Issue by migeed-z** [migeed-z/retic_performance#16]
The output file for http is empty.

**Comment by bennn** [comment]
When this happens you should:
1. Check whether any nodes have run `http2` configurations (they're in the `http2/Test` folder)
2. Check whether those nodes have a `node_output.txt` file. If so, that output's going to get appended to "the output file for http" next time `brun.py` runs.
3. If not, check the node's output/error file.

In this case, there's a folder `http2/Test/1798897.m2/` and I don't see any output for the node. So steps `2,3` both fail. 

I guess we'll just put the node's inputs back on the main input queue.
