### ISSUE TITLE
Thesis Statements

### ISSUE THREAD

**Issue by bennn** [migeed-z/retic_performance#19]
- Draft overall thesis for the article
- Draft thesis statements for each section 

(Zeina's doing first drafts, then she and I will talk together, then meeting with Matthias 2017-03-20)

**Comment by bennn** [comment]
Zeina has draft thesis statements. She's writing them up now, will commit "soon".

**Comment by bennn** [comment]
And once Zeina commits those, my job is to give feedback & suggest revisions until we have something I'm proud to present to Matthias

**Comment by bennn** [comment]
Zeina committed https://github.com/migeed-z/retic_performance/commit/038deff034384676d9295b418927329c5f77bb31

My comments:
- in `benchmarks.scrbl`,
  - replace "give an introduction" with a list of things we'll talk about --- what specific properties we want to tell you
  - I don't think the benchmarks' origin belongs in the thesis. If you decide to keep it, replace '"real life code" ?' with something professional. No question marks allowed.
  - were any benchmarks actually written "for the purpose of this paper"?
- in `conclusion.scrbl`,
  - don't say "in this section" for the conclusion
  - I know you don't have results yet, so write a thesis with free variables.  (I think you should be able to write a much better thesis using free variables --- let me know if what I'm asking for isn't clear)
- in `evaluation_criteria.scrbl`,
  - what is this!? No way. Try again, the thesis is not allowed to just restate the section title.
- in `experience.scrbl`
  - maybe this section doesn't belong in the paper, do you want to talk about removing it?
  - fix the typos
  - remove the parenthetical about union types
- in `introduction.scrbl`
  - Try again. Please proofread it for next time. This thesis statement needs to be the thesis for the entire paper. Think about all the things we're going to present --- make a list? --- and try distilling that into a sentence. 
- in `methodology.scrbl`
  - meta question: what's the difference between this section and evaluation criterion? Let's figure this out before we think more about writing those sections thesis statements.
- in `reticulated.scrbl`
  - Just say what reticulated is. Section 2 of the JFP paper is a decent model.
- in `threats.scrbl`
  - be more specific! Since you have the list of limitations, try to classify those as tight as possible. See the JFP paper.

**Comment by migeed-z** [comment]
I am a bit confused by some of the comments. We discussed that a thesis statement tells us what the section is and why we are reading it. At least that's my understanding. Defining reticulated python as a thesis statement doesn't make sense then because it doesn't tell us why we're reading this section. 

Also, you mentioned I should distil the introduction into a sentence. So a thesis statement should not exceed a sentence or is that just for the introduction? (or is the definition of reticulated python going to be a sentence too?)

**Comment by bennn** [comment]
Section 2 of the journal paper is titled "Typed Racket". It's first sentence is:

> Typed Racket is the oldest and most developed implementation of sound gradual typing.

This sentence makes a claim, the rest of the paragraph supports the claim. I'm saying, you should try writing a claim like that for reticulated.

Do you have time to work on this today?

**Comment by migeed-z** [comment]
I can try to work on it today during the evening, but I'm a bit busy before that

**Comment by bennn** [comment]
Ok please do

**Comment by bennn** [comment]
I didn't see the changes [here](https://github.com/migeed-z/retic_performance/commit/b9d72dbb9943cc489229b1fdf3858d246303f818) earlier. Please still try again tonight.

Two things:

1. Showing a correlation between performance and the number of types is NOT an important result. It's obvious. The question is: how bad is the overhead? What does the OVERALL performance look like using the Takikawa et al method.
2. Please read: http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/
