### ISSUE TITLE
Validate outputs

### ISSUE THREAD

**Issue by bennn** [migeed-z/retic_performance#7]
We have outputs for a few benchmarks. Need to check that:
- the data is well-formed & there's not too much variation between runs
- we can locally reproduce the runtimes for a few random configs
- duplicate configs have similar data
- after removing duplicates, we have data for all configurations

**Comment by bennn** [comment]
Here are the outputs
[karst-2016-10-01.zip](https://github.com/migeed-z/retic_performance/files/514797/karst-2016-10-01.zip)

**Comment by migeed-z** [comment]
This zip file appears to me empty

**Comment by migeed-z** [comment]
- Evolution data I think everything is wrong. Everything runs in about 0.2 seconds. 
- Pythonflow, getting this error when running the benchmark from karst:
  `File "/N/u/zmahmoud/Karst/reticulated/retic.py", line 5, in <module>
  retic.main()
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/retic.py", line 155, in main
    reticulate(program, prog_args=args.args.split(), flag_sets=args)
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/retic.py", line 104, in reticulate
    utils.handle_runtime_error(exit=True)
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/retic.py", line 102, in reticulate
    _exec(code, __main__.__dict__)
  File "/gpfs/home/z/m/zmahmoud/Karst/reticulated/retic/exec3/__init__.py", line 2, in _exec
    exec (obj, globs, locs)
  File "main.py", line 10, in <module>
    from Timer import Timer
  ImportError: No module named 'Timer'
  `

**Comment by bennn** [comment]
You need to copy all the files from the `both/` directory before you run any project's `main.py`

**Comment by bennn** [comment]
Sorry about the zipfile, it's fixed above.

**Comment by bennn** [comment]
take5 was missing 10,000 configs. These are now on the cluster as `karst_input.txt9` and attached here.
[take5_missing.txt](https://github.com/migeed-z/retic_performance/files/516474/take5_missing.txt)

Otherwise, the output had 3 copies of configuration `0-0-0` and everything else was good.

**Comment by bennn** [comment]
- Espionage had 228 duplicates, all with similar numbers
- PythonFlow had 150 duplicates, all with similar numbers

I've saved results for those benchmarks. They're "all done"
- futen had 142 duplicates (boring) but also 321 missing configs.

Missing = the data was like:

```
14-1-510    0    [[Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, ]
14-1-511    0    [[Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, ]
14-1-512    0    [[Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, [Errno, ]
```

I've setup these 321 configs to re-run on the cluster `retic_performance/futen/karst_input.txt9`

**Comment by bennn** [comment]
Here are the futen configs to re-run:
[futen_input.txt](https://github.com/migeed-z/retic_performance/files/517529/futen_input.txt)

Also I pushed the script I used to validate these files. Just run `python ValidateResults.py <path-to-data-file>`.
It assumes you made a `Benchmark/` folder for the benchmark.

**Comment by migeed-z** [comment]
Hey Ben, I'm not sure if this is a problem, but now we have 70 configs left and the output file has some errors. I attached it below. Is this the expected file? 
[karst_output.txt.zip](https://github.com/migeed-z/retic_performance/files/520764/karst_output.txt.zip)

**Comment by bennn** [comment]
Yes, the `Errno` and missing outputs are a problem.

What benchmark is this for?

Can you try running configurations like `242-6-7` and `253-1-5` to see if they work at all?

**Comment by migeed-z** [comment]
Opps, sorry, this is futen

**Comment by bennn** [comment]
That's interesting, those configurations aren't valid `futen` configurations.
(There's also a `30-3-23-0-7` in there, which is obviously bad because futen only has 3 modules)

I'll look more this afternoon. If you have time today, try running futen configuration `15-1-590`.
That's a valid futen configuration with bad data.

**Comment by migeed-z** [comment]
Okay this confiuration runs and finishes in 2.4234643240000002

**Comment by migeed-z** [comment]
When run on the cluster it runs in  2.452205759
